data:
    image: gitlab_data
    command: /bin/true
app:
    image: gitlab_app:latest
    ports:
        - "4080:80"
#        - "4443:443"
        - "2222:22"
    volumes_from:
        - data
    environment:
        - VIRTUAL_HOST=gitlab.mikuru.tw
