hub:
  image: selenium/hub
  ports:
    - "4444:4444"

chrome:
  image: selenium/node-chrome
  links:
    - hub:hub

firefox:
  image: selenium/node-firefox-debug
  links:
    - hub:hub
  ports:
    - "5900:5900"
